import type { Locale } from '@/utilities/locale'

/** Labels describe the method, never invented project results. */
const labels = {
  en: [
    'Working model',
    'Illustrative',
    'Research',
    'Constraints',
    'Baseline',
    'Problem to solve',
    'Success criteria',
    'People',
    'Business',
    'Operations',
    'Data & technology',
    'Product experience',
    'Build now',
    'Test next',
    'Leave out',
    'Core journey',
    'Key assumption',
    'Extra features',
    'Ready to use',
    'Design',
    'Build',
    'Operate',
    'One complete journey',
    'Observed',
    'Target',
    'Learn',
    'Next decision',
  ],
  fa: [
    'مدل کار',
    'نمایش مفهومی',
    'پژوهش',
    'محدودیت‌ها',
    'وضعیت فعلی',
    'مسئله‌ای که باید حل شود',
    'معیار موفقیت',
    'آدم‌ها',
    'کسب‌وکار',
    'عملیات',
    'داده و فناوری',
    'تجربه‌ی محصول',
    'اکنون بساز',
    'بعد آزمایش کن',
    'کنار بگذار',
    'مسیر اصلی',
    'فرض کلیدی',
    'امکانات اضافی',
    'آماده‌ی استفاده',
    'طراحی',
    'ساخت',
    'اجرا',
    'یک مسیر کامل',
    'مشاهده',
    'هدف',
    'یادگیری',
    'تصمیم بعدی',
  ],
  ar: [
    'نموذج العمل',
    'رسم توضيحي',
    'البحث',
    'القيود',
    'الوضع الحالي',
    'المشكلة المراد حلها',
    'معيار النجاح',
    'الأشخاص',
    'الأعمال',
    'العمليات',
    'البيانات والتقنية',
    'تجربة المنتج',
    'ابنِ الآن',
    'اختبر لاحقًا',
    'استبعد',
    'المسار الأساسي',
    'الافتراض الرئيسي',
    'ميزات إضافية',
    'جاهز للاستخدام',
    'التصميم',
    'البناء',
    'التشغيل',
    'مسار متكامل',
    'الملاحظ',
    'الهدف',
    'التعلّم',
    'القرار التالي',
  ],
  es: [
    'Modelo de trabajo',
    'Ilustrativo',
    'Investigación',
    'Restricciones',
    'Punto de partida',
    'Problema por resolver',
    'Criterio de éxito',
    'Personas',
    'Negocio',
    'Operaciones',
    'Datos y tecnología',
    'Experiencia de producto',
    'Construir ahora',
    'Probar después',
    'Descartar',
    'Recorrido principal',
    'Hipótesis clave',
    'Funciones extra',
    'Listo para usar',
    'Diseñar',
    'Construir',
    'Operar',
    'Un recorrido completo',
    'Observado',
    'Objetivo',
    'Aprender',
    'Siguiente decisión',
  ],
  de: [
    'Arbeitsmodell',
    'Schematisch',
    'Recherche',
    'Rahmenbedingungen',
    'Ausgangslage',
    'Das zu lösende Problem',
    'Erfolgskriterium',
    'Menschen',
    'Geschäft',
    'Betrieb',
    'Daten & Technik',
    'Produkterlebnis',
    'Jetzt bauen',
    'Danach testen',
    'Weglassen',
    'Kernablauf',
    'Zentrale Annahme',
    'Zusatzfunktionen',
    'Einsatzbereit',
    'Gestalten',
    'Bauen',
    'Betreiben',
    'Ein kompletter Ablauf',
    'Beobachtet',
    'Ziel',
    'Lernen',
    'Nächste Entscheidung',
  ],
  fr: [
    'Modèle de travail',
    'Illustration',
    'Recherche',
    'Contraintes',
    'État initial',
    'Le problème à résoudre',
    'Critère de réussite',
    'Personnes',
    'Activité',
    'Opérations',
    'Données et technique',
    'Expérience produit',
    'Construire maintenant',
    'Tester ensuite',
    'Écarter',
    'Parcours principal',
    'Hypothèse clé',
    'Fonctions en plus',
    'Prêt à utiliser',
    'Concevoir',
    'Construire',
    'Exploiter',
    'Un parcours complet',
    'Observé',
    'Cible',
    'Apprendre',
    'Prochaine décision',
  ],
  ja: [
    '作業モデル',
    '概念図',
    'リサーチ',
    '制約',
    '現状',
    '解決すべき課題',
    '成功の基準',
    '人',
    'ビジネス',
    '運用',
    'データと技術',
    'プロダクト体験',
    '今つくる',
    '次に検証',
    '対象外',
    '主要な体験',
    '重要な仮説',
    '追加機能',
    '利用可能',
    '設計',
    '開発',
    '運用',
    '一つの完全な体験',
    '観測',
    '目標',
    '学習',
    '次の意思決定',
  ],
} satisfies Record<Locale, string[]>

export function visualCopy(locale: Locale) {
  const [
    model,
    illustrative,
    research,
    constraints,
    baseline,
    problem,
    success,
    people,
    business,
    operations,
    technology,
    experience,
    now,
    next,
    later,
    journey,
    assumption,
    extras,
    ready,
    design,
    build,
    operate,
    complete,
    observed,
    target,
    learn,
    decision,
  ] = labels[locale]
  return {
    model,
    illustrative,
    research,
    constraints,
    baseline,
    problem,
    success,
    people,
    business,
    operations,
    technology,
    experience,
    now,
    next,
    later,
    journey,
    assumption,
    extras,
    ready,
    design,
    build,
    operate,
    complete,
    observed,
    target,
    learn,
    decision,
  }
}

export const visualCaptions: Record<Locale, readonly [string, string, string, string, string]> = {
  en: [
    'Turn assumptions into a testable problem.',
    'Connect the experience to the system behind it.',
    'Make the trade-offs explicit before building.',
    'Deliver the journey and the operations behind it.',
    'Compare the evidence, then choose the next move.',
  ],
  fa: [
    'از فرض‌های پراکنده به مسئله‌ای قابل‌آزمون برس.',
    'تجربه را به سیستم پشت آن وصل کن.',
    'پیش از ساخت، انتخاب‌ها و حذف‌ها را روشن کن.',
    'مسیر کاربر و عملیات پشت آن را با هم تحویل بده.',
    'شواهد را مقایسه کن و قدم بعدی را انتخاب کن.',
  ],
  ar: [
    'حوّل الافتراضات إلى مشكلة قابلة للاختبار.',
    'اربط التجربة بالنظام الذي يدعمها.',
    'وضّح المفاضلات قبل البناء.',
    'سلّم الرحلة والعمليات التي تدعمها.',
    'قارن الأدلة ثم حدّد الخطوة التالية.',
  ],
  es: [
    'Convierte supuestos en un problema comprobable.',
    'Conecta la experiencia con el sistema que la sostiene.',
    'Aclara las prioridades antes de construir.',
    'Entrega el recorrido y las operaciones que lo sostienen.',
    'Compara la evidencia y elige el siguiente paso.',
  ],
  de: [
    'Aus Annahmen wird ein überprüfbares Problem.',
    'Verbinde das Erlebnis mit dem System dahinter.',
    'Kläre die Abwägungen vor der Umsetzung.',
    'Liefere den Ablauf und den Betrieb dahinter.',
    'Vergleiche die Erkenntnisse und wähle den nächsten Schritt.',
  ],
  fr: [
    'Transformez les hypothèses en un problème vérifiable.',
    'Reliez l’expérience au système qui la soutient.',
    'Clarifiez les arbitrages avant de construire.',
    'Livrez le parcours et les opérations qui le soutiennent.',
    'Comparez les observations, puis choisissez la suite.',
  ],
  ja: [
    '仮説を検証できる課題に変える。',
    '体験と、その背後の仕組みをつなぐ。',
    'つくる前に、選択と取捨選択を明確にする。',
    '利用体験と運用を一体で届ける。',
    '観測した事実を比較し、次の一手を決める。',
  ],
}
