import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'

// eslint-config-next@16 ships flat-config arrays; the old FlatCompat.extends()
// bridge choked on them ("Converting circular structure to JSON").
const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    // Same file set as eslint-config-next's own block, so its plugins are in scope here.
    files: ['**/*.{js,jsx,mjs,ts,tsx,mts,cts}'],
    rules: {
      // eslint-config-next@16 adds the React Compiler rules; the template's providers/Card
      // predate them, so they warn until that code is rewritten.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          args: 'after-used',
          ignoreRestSiblings: false,
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^(_|ignore)',
        },
      ],
    },
  },
  {
    ignores: [
      '.next/',
      'src/payload-types.ts',
      'src/payload-generated-schema.ts',
      // generated by `pnpm tokens:build`
      'src/app/(frontend)/theme.css',
      'src/cssVariables.js',
    ],
  },
]

export default eslintConfig
