/**
 * Pure emitters: house tokens (DTCG JSON) → Tailwind v4 theme CSS and the
 * breakpoint mirror for next/image `sizes`. No file IO here — see ../build.ts.
 */
import { TOKEN_GROUPS } from '../../docs/lib/schema'
import { ext, flattenTokens, isToken, type FlatEntry, type Group, type Token, type TokensFile } from '../../docs/lib/tokens'

export const GENERATED_HEADER =
  'GENERATED by `pnpm tokens:build` from Docs/Design-System/tokens/sina.tokens.json — do not edit, edit the tokens'

export const THEME_SELECTORS = {
  light: ":root, [data-theme='light']",
  dark: "[data-theme='dark']",
} as const
export type ThemeName = keyof typeof THEME_SELECTORS
/** Locale token overrides (e.g. `font.fa.*`, `font.ar.*`) are emitted inside their own selector. */
export const LOCALE_OVERRIDE_SELECTORS: Record<string, string> = {
  fa: ':lang(fa)',
  ar: ':lang(ar)',
}

// ---------------------------------------------------------------------------
// Names

type Rule = [RegExp, (m: RegExpExecArray) => string]
const RULES: Rule[] = [
  [/^color\.(light|dark)\.([a-z0-9-]+)$/, (m) => `--${m[2]}`],
  [/^font\.family\.([a-z0-9-]+)$/, (m) => `--font-${m[1]}`],
  [/^font\.size\.([a-z0-9-]+)$/, (m) => `--text-${m[1]}`],
  [/^font\.leading\.([a-z0-9-]+)$/, (m) => `--leading-${m[1]}`],
  [/^font\.tracking\.([a-z0-9-]+)$/, (m) => `--tracking-${m[1]}`],
  [/^font\.weight\.([a-z0-9-]+)$/, (m) => `--font-weight-${m[1]}`],
  [/^space\.([a-z0-9-]+)$/, (m) => `--spacing-${m[1]}`],
  [/^size\.container$/, () => '--container-page'],
  [/^size\.measure$/, () => '--container-measure'],
  [/^size\.control\.([a-z0-9-]+)$/, (m) => `--size-control-${m[1]}`],
  [/^radius\.([a-z0-9-]+)$/, (m) => `--radius-${m[1]}`],
  [/^motion\.ease\.([a-z0-9-]+)$/, (m) => `--ease-${m[1]}`],
  [/^motion\.duration\.([a-z0-9-]+)$/, (m) => `--duration-${m[1]}`],
  [/^motion\.lift$/, () => '--lift'],
  [/^breakpoint\.([a-z0-9-]+)$/, (m) => `--breakpoint-${m[1]}`],
]

const LOCALE_OVERRIDE_RE = new RegExp(`^([a-z]+)\\.(${Object.keys(LOCALE_OVERRIDE_SELECTORS).join('|')})\\.`)

/** `font.fa.leading.body` → `font.leading.body` (locale overrides reuse the base names). */
export const baseOf = (path: string) => path.replace(LOCALE_OVERRIDE_RE, '$1.')
/** The override locale a path belongs to (e.g. `fa`), or null for a base token. */
export const overrideLocale = (path: string): string | null => LOCALE_OVERRIDE_RE.exec(path)?.[2] ?? null
export const themeOf = (path: string): ThemeName | null => {
  const m = /^color\.(light|dark)\./.exec(path)
  return m ? (m[1] as ThemeName) : null
}

/** CSS custom property a token path is emitted as. Throws on paths the emitter does not know. */
export function cssName(path: string): string {
  const base = baseOf(path)
  for (const [re, name] of RULES) {
    const m = re.exec(base)
    if (m) return name(m)
  }
  throw new Error(`tokens: no CSS mapping for "${path}" — add a rule in scripts/tokens/lib/emit.ts`)
}

// ---------------------------------------------------------------------------
// Values

const num = (n: number) => {
  const s = Number(n.toFixed(4)).toString()
  return s === '-0' ? '0' : s
}

const GENERIC = new Set([
  'serif', 'sans-serif', 'monospace', 'cursive', 'fantasy', 'system-ui', 'ui-serif', 'ui-sans-serif',
  'ui-monospace', 'ui-rounded', 'emoji', 'math', 'fangsong', 'inherit',
])
const familyName = (n: string) => (GENERIC.has(n) || n.startsWith('var(') || n.startsWith('-') ? n : `"${n}"`)

type Dim = { value: number; unit: string }
type Color = { colorSpace: string; components: number[]; hex?: string; alpha?: number }

function formatColor(v: Color): string {
  const a = v.alpha !== undefined && v.alpha < 1 ? ` / ${num(v.alpha)}` : ''
  if (v.colorSpace === 'oklch') {
    const [l = 0, c = 0, h = 0] = v.components
    return `oklch(${num(l * 100)}% ${num(c)} ${num(h)}${a})`
  }
  if (v.hex && !a) return v.hex.toLowerCase()
  const [r = 0, g = 0, b = 0] = v.components.map((x) => Math.round(x * 255))
  return `rgb(${r} ${g} ${b}${a})`
}

const formatDim = (d: Dim) => `${num(d.value)}${d.unit}`
const isDim = (v: unknown): v is Dim =>
  !!v && typeof v === 'object' && typeof (v as Dim).value === 'number' && typeof (v as Dim).unit === 'string'
const isColor = (v: unknown): v is Color =>
  !!v && typeof v === 'object' && Array.isArray((v as Color).components)

const ALIAS = /^\{([a-z][a-zA-Z0-9]*(?:\.[a-z0-9][a-zA-Z0-9-]*)+)\}$/

/** CSS value of a leaf token or fluid group. */
export function cssValue(entry: FlatEntry): string {
  if (entry.kind === 'fluid') {
    const g = entry.node as Group
    const min = (g.min as Token | undefined)?.$value
    const vw = (g.vw as Token | undefined)?.$value
    const max = (g.max as Token | undefined)?.$value
    if (!isDim(min) || typeof vw !== 'number' || !isDim(max))
      throw new Error(`tokens: fluid group ${entry.path} needs min/vw/max`)
    return `clamp(${formatDim(min)}, ${num(vw)}${ext(g).vwUnit ?? 'vw'}, ${formatDim(max)})`
  }
  const v = (entry.node as Token).$value
  if (typeof v === 'string') {
    const m = ALIAS.exec(v)
    if (m) return `var(${cssName(m[1]!)})`
    return v
  }
  switch (entry.type) {
    case 'color':
      if (!isColor(v)) throw new Error(`tokens: ${entry.path} is not a colour object`)
      return formatColor(v)
    case 'dimension':
    case 'duration':
      if (!isDim(v)) throw new Error(`tokens: ${entry.path} is not { value, unit }`)
      return formatDim(v)
    case 'cubicBezier':
      if (!Array.isArray(v) || v.length !== 4) throw new Error(`tokens: ${entry.path} is not a 4-number bezier`)
      return `cubic-bezier(${(v as number[]).map(num).join(', ')})`
    case 'fontFamily': {
      if (!Array.isArray(v)) throw new Error(`tokens: ${entry.path} is not a family list`)
      const names = [...(v as string[])]
      const varName = ext(entry.node).var
      if (varName) names[0] = `var(${varName})`
      return names.map(familyName).join(', ')
    }
    case 'number':
    case 'fontWeight':
      if (typeof v !== 'number') throw new Error(`tokens: ${entry.path} is not a number`)
      return num(v)
    default:
      throw new Error(`tokens: ${entry.path} has unsupported $type "${entry.type}"`)
  }
}

// ---------------------------------------------------------------------------
// theme.css

const groupIndex = (path: string) => {
  const i = (TOKEN_GROUPS as readonly string[]).indexOf(path.split('.')[0]!)
  return i === -1 ? TOKEN_GROUPS.length : i
}

/** Leaf tokens and fluid groups, minus the min/vw/max children of fluid groups, in emit order. */
export function emitEntries(json: TokensFile): FlatEntry[] {
  const all = flattenTokens(json)
  const fluid = new Set(all.filter((e) => e.kind === 'fluid').map((e) => e.path))
  return all
    .filter((e) => !fluid.has(e.path.slice(0, e.path.lastIndexOf('.'))))
    .sort((a, b) => groupIndex(a.path) - groupIndex(b.path) || a.path.localeCompare(b.path))
}

const block = (selector: string, lines: string[]) =>
  lines.length ? `${selector} {\n${lines.map((l) => `  ${l}`).join('\n')}\n}\n` : ''

const role = (path: string) => path.split('.').pop()!

export function emitThemeCss(json: TokensFile): string {
  const entries = emitEntries(json)
  const byPath = new Map(entries.map((e) => [e.path, e]))
  const has = (p: string) => byPath.has(p)

  const theme: string[] = []
  const scopes: Record<ThemeName, string[]> = { light: [], dark: [] }
  const localeOverrides: Record<string, string[]> = Object.fromEntries(
    Object.keys(LOCALE_OVERRIDE_SELECTORS).map((locale) => [locale, []]),
  )
  const colorNames = new Set<string>()

  for (const e of entries) {
    const decl = `${cssName(e.path)}: ${cssValue(e)};`
    const t = themeOf(e.path)
    if (t) {
      scopes[t].push(decl)
      colorNames.add(role(e.path))
      continue
    }
    const locale = overrideLocale(e.path)
    if (locale) {
      const base = baseOf(e.path)
      if (!has(base)) throw new Error(`tokens: ${e.path} overrides ${base}, which does not exist`)
      const bucket = localeOverrides[locale]!
      bucket.push(decl)
      // Companion vars are resolved where declared, so the override must restate them.
      const m = /^font\.(leading|tracking)\.([a-z0-9-]+)$/.exec(base)
      if (m && has(`font.size.${m[2]}`))
        bucket.push(`--text-${m[2]}--${m[1] === 'leading' ? 'line-height' : 'letter-spacing'}: ${cssValue(e)};`)
      continue
    }
    theme.push(decl)
    const m = /^font\.size\.([a-z0-9-]+)$/.exec(e.path)
    if (m) {
      const lead = byPath.get(`font.leading.${m[1]}`)
      const track = byPath.get(`font.tracking.${m[1]}`)
      if (lead) theme.push(`--text-${m[1]}--line-height: ${cssValue(lead)};`)
      if (track) theme.push(`--text-${m[1]}--letter-spacing: ${cssValue(track)};`)
    }
  }

  const light = new Set(scopes.light.map((d) => d.split(':')[0]))
  const dark = new Set(scopes.dark.map((d) => d.split(':')[0]))
  for (const n of light) if (!dark.has(n)) throw new Error(`tokens: ${n} is defined for light but not dark`)
  for (const n of dark) if (!light.has(n)) throw new Error(`tokens: ${n} is defined for dark but not light`)

  const bridge = [...colorNames].sort().map((n) => `--color-${n}: var(--${n});`)

  return [
    `/* ${GENERATED_HEADER} */\n`,
    `/* Type, space, size, radius, motion, breakpoints. \`static\` keeps every variable in the CSS even when no utility uses it. */`,
    block('@theme static', theme),
    `/* Colour roles per theme + the shadcn slots as aliases. Aliases are repeated per scope on purpose: a var() inside a custom property resolves where it is declared. */`,
    block(THEME_SELECTORS.light, scopes.light),
    block(THEME_SELECTORS.dark, scopes.dark),
    `/* Colour utilities (bg-paper, text-ink-2, border-line …) read the live variable. */`,
    block('@theme inline', bridge),
    `/* Persian overrides — same variables, script-specific values (D-016). */`,
    block(LOCALE_OVERRIDE_SELECTORS.fa!, localeOverrides.fa!),
    `/* Arabic overrides — same variables; Vazirmatn already covers the Arabic subset. */`,
    block(LOCALE_OVERRIDE_SELECTORS.ar!, localeOverrides.ar!),
  ]
    .filter(Boolean)
    .join('\n')
}

// ---------------------------------------------------------------------------
// cssVariables.js

export function emitCssVariablesJs(json: TokensFile): string {
  const bp = emitEntries(json)
    .filter((e) => e.path.startsWith('breakpoint.') && e.kind === 'token')
    .map((e) => {
      const v = (e.node as Token).$value
      if (!isDim(v)) throw new Error(`tokens: ${e.path} is not { value, unit }`)
      const px = v.unit === 'rem' ? v.value * 16 : v.unit === 'px' ? v.value : NaN
      if (Number.isNaN(px)) throw new Error(`tokens: ${e.path} must be rem or px`)
      return [role(e.path), Math.round(px)] as const
    })
    .sort((a, b) => b[1] - a[1])
  const key = (k: string) => (/^[a-z_$][\w$]*$/i.test(k) ? k : `'${k}'`)
  return [
    `// ${GENERATED_HEADER}`,
    '// Breakpoints in px, for next/image `sizes` hints (see ImageMedia).',
    '',
    'export const cssVariables = {',
    '  breakpoints: {',
    ...bp.map(([k, v]) => `    ${key(k)}: ${v},`),
    '  },',
    '}',
    '',
  ].join('\n')
}

export { isToken }
