// GENERATED by `pnpm tokens:build` from Docs/Design-System/tokens/sina.tokens.json — do not edit, edit the tokens
// Breakpoints in px, for next/image `sizes` hints (see ImageMedia).

export const cssVariables = {
  breakpoints: {
    '2xl': 1376,
    xl: 1280,
    lg: 1024,
    md: 768,
    sm: 640,
  },
}
