/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    projects: Project;
    media: Media;
    categories: Category;
    experiences: Experience;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'fa' | 'ar' | 'es' | 'de' | 'fr' | 'ja')
    | ('en' | 'fa' | 'ar' | 'es' | 'de' | 'fr' | 'ja')[];
  globals: {
    header: Header;
    footer: Footer;
    about: About;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
  };
  locale: 'en' | 'fa' | 'ar' | 'es' | 'de' | 'fr' | 'ja';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'homeImpact' | 'aboutImpact' | 'experienceImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null)
              | ({
                  relationTo: 'projects';
                  value: string | Project;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | MetricsStripBlock
    | SelectedWorkBlock
    | WorkMosaicBlock
    | WorkspaceBlock
    | TracksBlock
    | WorkflowStagesBlock
    | ExperienceCatalogueBlock
    | ExperienceTeaserBlock
    | CapabilitySpotlightBlock
    | CapabilityMatrixBlock
    | CapabilityEvidenceBlock
    | CapabilityModelBlock
    | ProjectArchiveBlock
    | CareerJourneyBlock
    | ThinkingMapBlock
    | PrinciplesBlock
    | TeamProcessBlock
    | PersonalSideBlock
    | NowSectionBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Tick per language once a native speaker has reviewed this locale. Machine-drafted locales stay unticked.
   */
  translationReviewed?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * What a project is: title, organisation, role, one-paragraph summary, cover. How it appears is decided by the page that references it. Publish a project to list it on /work; set "Case study" to published only once /work/<slug> has real content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  /**
   * Organisation or product owner — "Independent" for freelance work.
   */
  company: string;
  /**
   * Sina's role on this project, e.g. "Product designer".
   */
  role?: string | null;
  /**
   * One or two sentences — source-backed, no unverified outcomes or numbers.
   */
  summary: string;
  /**
   * The nature of the work (not the tools). One or two values; drives the /work filter.
   */
  kind?: ('product' | 'growth' | 'data' | 'research' | 'systems' | 'concept')[] | null;
  /**
   * Leave empty until dates are confirmed — the archive shows the organisation instead.
   */
  period?: {
    start?: string | null;
    end?: string | null;
    present?: boolean | null;
  };
  /**
   * e.g. "Gaming · play-to-earn". Free text until a domain taxonomy is decided (Content-Model §13).
   */
  industry?: string | null;
  /**
   * Who else was on it, one line — roles, not names unless public.
   */
  team?: string | null;
  /**
   * Shown in the case-study header; labels are translated in code.
   */
  projectStatus?: ('shipped' | 'in-progress' | 'pre-launch' | 'paused' | 'concept') | null;
  /**
   * Tool names in Latin — not translated.
   */
  tools?: string[] | null;
  /**
   * Real project evidence — UI, dashboard, artifact. Portrait screens are fine; the page frames them instead of cropping. Leave empty to show the "media pending" placeholder.
   */
  cover?: (string | null) | Media;
  /**
   * Optional. A live product or external page; archive rows show it with an outward arrow.
   */
  liveUrl?: string | null;
  /**
   * One-line positioning under the title — "Building a digital gold product from proposition to growth system." Falls back to the summary.
   */
  statement?: string | null;
  hero?: CaseStudyHero;
  snapshot?: CaseStudySnapshot;
  sections?:
    | (
        | CaseStudyNarrativeBlock
        | CaseStudyFigureBlock
        | CaseStudyFindingBlock
        | CaseStudyProcessBlock
        | CaseStudyOwnershipBlock
        | CaseStudyDecisionsBlock
        | CaseStudyOutcomesBlock
        | CaseStudyLessonsBlock
      )[]
    | null;
  /**
   * Optional. Empty = the next published case study by order (wrapping around).
   */
  nextProject?: (string | null) | Project;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * Show in the featured section at the top of /work (the first three by order).
   */
  featured?: boolean | null;
  /**
   * Editorial order on /work — lower first. Featured projects use the same number.
   */
  order: number;
  /**
   * Separate from publishing the project: only "Published" turns archive rows into links.
   */
  caseStudyStatus: 'none' | 'draft' | 'published';
  /**
   * Tick per language once a native speaker has reviewed this locale. Machine-drafted locales stay unticked.
   */
  translationReviewed?: boolean | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One dominant visual after the header. One item = a full-width visual; two or three = a row of screens on a panel. Portrait phone captures are framed, never mocked into a device.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyHero".
 */
export interface CaseStudyHero {
  items?:
    | {
        media: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * What the hero shows and why it matters.
   */
  caption?: string | null;
}
/**
 * One sentence each — a reader should get the whole case in ten seconds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudySnapshot".
 */
export interface CaseStudySnapshot {
  problem?: string | null;
  role?: string | null;
  result?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyNarrativeBlock".
 */
export interface CaseStudyNarrativeBlock {
  /**
   * Opens a numbered chapter ("01 CONTEXT"). Labels are translated in code.
   */
  label: 'context' | 'problem' | 'constraints' | 'approach' | 'solution' | 'research' | 'outcome' | 'custom';
  /**
   * Short — one or two words.
   */
  customLabel?: string | null;
  /**
   * A short verdict, not a label — e.g. "Competitive and rewarding without becoming a casino."
   */
  heading: string;
  /**
   * Two to four sentences per chapter reads best; lists are fine for constraints.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional one-sentence takeaway, set as a pull line after the body — the line you would want someone to remember.
   */
  insight?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csNarrative';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyFigureBlock".
 */
export interface CaseStudyFigureBlock {
  layout: 'full' | 'split' | 'sequence' | 'annotated' | 'compare';
  /**
   * What the media is, not how big it should be.
   */
  treatment?: ('auto' | 'screen' | 'plain' | 'diagram') | null;
  /**
   * Full / annotated: exactly one. Split / compare: exactly two. Sequence: two to four.
   */
  items?:
    | {
        media: string | Media;
        /**
         * Optional per-visual note; keep the explanation in the figure caption below.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Numbered key rendered beside the visual (01, 02 …). Number the callouts on the image to match.
   */
  annotations?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * What we are looking at and why it matters — not a repeat of the visible UI.
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csFigure';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyFindingBlock".
 */
export interface CaseStudyFindingBlock {
  kind: 'finding' | 'quote';
  text: string;
  /**
   * Who or what it comes from, e.g. "RP1 tone guideline".
   */
  attribution?: string | null;
  /**
   * How it was gathered, e.g. "8 interviews, aggregated".
   */
  method?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csFinding';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyProcessBlock".
 */
export interface CaseStudyProcessBlock {
  /**
   * Optional short title, e.g. "Six passes, in order".
   */
  heading?: string | null;
  kind?: ('process' | 'loop') | null;
  steps?:
    | {
        /**
         * Latin code, e.g. "R1" — stays mono in every locale.
         */
        code: string;
        label: string;
        /**
         * Optional technical annotation under the label.
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csProcess';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyOwnershipBlock".
 */
export interface CaseStudyOwnershipBlock {
  /**
   * Optional — defaults to "My role" in the page language.
   */
  heading?: string | null;
  /**
   * Two to four sentences: scope, who else was involved, what was decided vs. contributed to.
   */
  intro?: string | null;
  /**
   * Areas Sina owned outright.
   */
  own?: string[] | null;
  /**
   * Shared with a named role.
   */
  coOwn?: string[] | null;
  /**
   * Owned by others; Sina contributed.
   */
  collaborate?: string[] | null;
  /**
   * Optional caveat — e.g. who owned engineering or marketing.
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csOwnership';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyDecisionsBlock".
 */
export interface CaseStudyDecisionsBlock {
  /**
   * Optional — defaults to "Key decisions" in the page language.
   */
  heading?: string | null;
  /**
   * One sentence framing the decisions (optional).
   */
  lede?: string | null;
  /**
   * Three to six decisions that materially shaped the result.
   */
  items?:
    | {
        /**
         * The decision as a statement — "Reduce onboarding from six steps to four."
         */
        title: string;
        /**
         * Why this direction was chosen.
         */
        why: string;
        /**
         * What else was considered.
         */
        alternatives?: string | null;
        /**
         * What was gained and what was given up.
         */
        tradeoff?: string | null;
        /**
         * What supported the decision — data, research, a documented log.
         */
        evidence?: string | null;
        /**
         * Optional small visual that shows the decision (not decoration).
         */
        media?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csDecisions';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyOutcomesBlock".
 */
export interface CaseStudyOutcomesBlock {
  /**
   * Optional — defaults to "Outcomes" in the page language.
   */
  heading?: string | null;
  /**
   * One or two sentences of context — including what cannot be reported yet.
   */
  intro?: string | null;
  items?:
    | {
        /**
         * Only a credible number — "34", "+18%". Leave empty for a qualitative outcome.
         */
        value?: string | null;
        /**
         * What it is — the statement itself when there is no number.
         */
        label: string;
        /**
         * Meaning and time frame.
         */
        context?: string | null;
        kind: 'measured' | 'delivered';
        /**
         * Provenance — dashboard, report, document, date.
         */
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional terse list of what actually shipped (DS-27).
   */
  shipped?: string[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csOutcomes';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyLessonsBlock".
 */
export interface CaseStudyLessonsBlock {
  /**
   * Optional — defaults to "What I learned" in the page language.
   */
  heading?: string | null;
  /**
   * A wrong assumption, what changed after launch, what would be done differently, a principle that became reusable.
   */
  items?:
    | {
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csLessons';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * Editorial: the first column is the heading side (5/12), the rest stack on the body side (7/12).
   */
  layout?: ('columns' | 'editorial') | null;
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsStripBlock".
 */
export interface MetricsStripBlock {
  sectionHeader?: SectionHeaderField;
  metrics?:
    | {
        /**
         * Short — "30%", "20+", "~$0.03"
         */
        value: string;
        /**
         * What the number measures
         */
        caption: string;
        /**
         * Where it comes from (report, dashboard, date) — every number is traceable
         */
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'metricsStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeaderField".
 */
export interface SectionHeaderField {
  /**
   * Short label on the rule, e.g. "Work" or "By the numbers"
   */
  tag?: string | null;
  /**
   * First part of the heading, in ink
   */
  lead?: string | null;
  /**
   * Second part of the heading, muted (optional)
   */
  tail?: string | null;
  /**
   * One or two sentences under the heading (optional)
   */
  lede?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SelectedWorkBlock".
 */
export interface SelectedWorkBlock {
  sectionHeader?: SectionHeaderField;
  /**
   * Project facts (title, organisation, role, summary, cover) come from the Projects collection. Publish the project in each language it should appear in.
   */
  project: string | Project;
  id?: string | null;
  blockName?: string | null;
  blockType: 'selectedWork';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkMosaicBlock".
 */
export interface WorkMosaicBlock {
  sectionHeader?: SectionHeaderField;
  /**
   * One tile per project, in reading order — drag to reorder. Size is a weight on a row: Wide fills a row, two halves (Large or Medium) fill a row, four quarters (Small) fill a row. Mix sizes so each row adds up, or the row will end in empty paper.
   */
  items: {
    /**
     * Project facts come from the Projects collection. Publish the project in each language it should appear in — a project left unpublished in a language is skipped there.
     */
    project: string | Project;
    /**
     * How much of a row this project claims, and how much it says.
     */
    size: 'wide' | 'large' | 'medium' | 'small';
    /**
     * Optional. Overrides what this tile shows. Leave empty to use the project cover, then the first case-study hero visual, then the pending plate.
     */
    mediaOverride?: (string | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'workMosaic';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkspaceBlock".
 */
export interface WorkspaceBlock {
  sectionHeader?: SectionHeaderField;
  /**
   * Ownership bracket label spanning the stage rail, e.g. "Own the problem — at every stage".
   */
  principle: string;
  /**
   * Return-edge caption under the rail, e.g. "Evidence reopens the model".
   */
  loopLabel: string;
  stages?:
    | {
        /**
         * Selects the bench visual state. Order on the page is fixed by key, not by this array.
         */
        key: 'frame' | 'map' | 'decide' | 'ship' | 'measure';
        label: string;
        /**
         * Short claim under the stage name in the rail (desktop) / panel h3 (mobile).
         */
        statement: string;
        /**
         * Core question shown as the desktop panel heading.
         */
        question: string;
        description: string;
        /**
         * What this stage produces, e.g. "Problem statement + success metric".
         */
        output: string;
        /**
         * Optional. Shown as “Seen in” only when the project has a published case study in the current locale.
         */
        evidence?: (string | null) | Project;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'workspace';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TracksBlock".
 */
export interface TracksBlock {
  sectionHeader?: SectionHeaderField;
  tracks?:
    | {
        key: 'productDesign' | 'aiWorkflow' | 'designSystems';
        title: string;
        /**
         * Optional short duration label, e.g. "10 yrs". Leave blank until source-verified.
         */
        experience?: string | null;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tracks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowStagesBlock".
 */
export interface WorkflowStagesBlock {
  sectionHeader?: SectionHeaderField;
  /**
   * Rendered in the canonical order defined in toolLogos.ts (01 Design & Creative Production → 07 Knowledge & Research). The two-digit index follows that order, not the row order here.
   */
  categories?:
    | {
        /**
         * Stable id — sets the render order and the index code
         */
        key:
          | 'designPrototyping'
          | 'aiAgents'
          | 'buildDelivery'
          | 'dataIntelligence'
          | 'growthMeasurement'
          | 'infraOperations'
          | 'knowledgeResearch';
        /**
         * Shown above the matrix, e.g. "Design & Creative Production"
         */
        title: string;
        tools?:
          | {
              /**
               * Resolves to a brand mark and its canonical product name (toolLogos.ts).
               */
              toolKey:
                | 'figma'
                | 'sketch'
                | 'afterEffects'
                | 'mediaEncoder'
                | 'higgsfield'
                | 'chatgpt'
                | 'claude'
                | 'gemini'
                | 'grok'
                | 'codex'
                | 'hermes'
                | 'grokBot'
                | 'openclaw'
                | 'openrouter'
                | 'langchain'
                | 'typesafeAi'
                | 'cursor'
                | 'antigravity'
                | 'vscode'
                | 'payloadCms'
                | 'nextjs'
                | 'docker'
                | 'ga4'
                | 'amplitude'
                | 'heap'
                | 'fullstory'
                | 'clarity'
                | 'hotjar'
                | 'umami'
                | 'googleTagManager'
                | 'googleAds'
                | 'googleSearchConsole'
                | 'supabase'
                | 'vercel'
                | 'coolify'
                | 'github'
                | 'gitlab'
                | 'gitea'
                | 'sentry'
                | 'obsidian';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'workflowStages';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExperienceCatalogueBlock".
 */
export interface ExperienceCatalogueBlock {
  sectionHeader?: SectionHeaderField;
  items?:
    | {
        /**
         * e.g. "A1"
         */
        index: string;
        name: string;
        /**
         * Resolves to a brand mark in companyLogos.ts. Leave empty for a text-only cell.
         */
        companyKey?:
          | (
              | 'tahaGasht'
              | 'digikala'
              | 'carsparency'
              | 'khodro45'
              | 'hadishMall'
              | 'fibona'
              | 'oteacher'
              | 'arvanCloud'
              | 'biomaze'
              | 'didestan'
              | 'a1paradise'
            )
          | null;
        /**
         * e.g. "Designer / Marketer / BI developer · 2.5 yr"
         */
        role: string;
        /**
         * Optional one-line description
         */
        blurb?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'experienceCatalogue';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExperienceTeaserBlock".
 */
export interface ExperienceTeaserBlock {
  sectionHeader?: SectionHeaderField;
  /**
   * The four primary capabilities, in reading order — drag to reorder. The index code (01, 02 …) follows this order. Each key selects a fixed mark that cannot be edited here. Keep these in step with the capability spotlight on /experience.
   */
  capabilities: {
    /**
     * Stable id — selects the mark
     */
    key: 'discovery' | 'service' | 'systems' | 'ai-execution';
    title: string;
    /**
     * One short declarative sentence, e.g. "Understand before building."
     */
    principle: string;
    id?: string | null;
  }[];
  /**
   * The proof beneath the capabilities — three or four at most. These support the section; they are not its subject.
   */
  metrics?:
    | {
        /**
         * Short — "10 yrs", "20+", "~$0.03"
         */
        value: string;
        /**
         * What the number measures
         */
        caption: string;
        /**
         * Where it comes from (report, dashboard, date) — every number is traceable. Stored for the editor, not rendered.
         */
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'experienceTeaser';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilitySpotlightBlock".
 */
export interface CapabilitySpotlightBlock {
  sectionHeader?: SectionHeaderField;
  /**
   * The four primary capabilities, in reading order — drag to reorder. The index code (001, 002 …) follows this order. Each key selects a fixed illustration that cannot be edited here.
   */
  items: {
    /**
     * Stable id — selects the illustration
     */
    key: 'discovery' | 'service' | 'systems' | 'ai-execution';
    title: string;
    /**
     * One short declarative sentence, e.g. "Understand before building."
     */
    principle: string;
    /**
     * Two lines at most — what the capability actually does
     */
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'capabilitySpotlight';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilityMatrixBlock".
 */
export interface CapabilityMatrixBlock {
  sectionHeader?: SectionHeaderField;
  /**
   * The small label above each capability’s evidence list, e.g. "Evidence". One string for the whole section rather than sixteen copies of the same word.
   */
  evidenceLabel: string;
  /**
   * The four capability groups, in reading order. Every one of the sixteen skills must appear exactly once, in its own group — the page is a complete inventory, so nothing may silently drop out of it.
   */
  groups: {
    /**
     * Stable id — fixes which skills may sit here
     */
    key: 'core' | 'systems' | 'execution' | 'specialized';
    /**
     * Group heading, e.g. "Core"
     */
    title: string;
    skills: {
      /**
       * Stable id — selects the mini mark
       */
      key:
        | 'ai-product-development'
        | 'analytics-experimentation'
        | 'business-modeling'
        | 'documentation-spec'
        | 'fintech-strategy'
        | 'gamification'
        | 'process-operations'
        | 'product-discovery'
        | 'product-function-setup'
        | 'product-management'
        | 'requirements'
        | 'rtl-persian'
        | 'service-design'
        | 'stakeholder-management'
        | 'technical-pm'
        | 'ux-direction';
      title: string;
      /**
       * One concise sentence. Not an essay.
       */
      description: string;
      /**
       * Where this capability was actually used. Attach the project when one exists — the label becomes a link on its own once that project has a published case study, and stays plain text until then.
       */
      evidence?:
        | {
            /**
             * Company or project as it should read
             */
            label: string;
            /**
             * Optional — links once a case study publishes
             */
            project?: (string | null) | Project;
            id?: string | null;
          }[]
        | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'capabilityMatrix';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilityEvidenceBlock".
 */
export interface CapabilityEvidenceBlock {
  sectionHeader?: SectionHeaderField;
  /**
   * Three to five examples where several capabilities combined. Attach the project when one exists — the title becomes a link on its own once that project has a published case study.
   */
  items: {
    /**
     * Company or project, e.g. "Digikala — Digital Gold"
     */
    label: string;
    /**
     * Optional — links once a case study publishes
     */
    project?: (string | null) | Project;
    /**
     * One line on what the work was (optional)
     */
    note?: string | null;
    /**
     * The capabilities that combined here. Use the short display form — these read as a sum, not as full skill titles.
     */
    capabilities: {
      /**
       * Selects the mini mark
       */
      key:
        | 'product-management'
        | 'product-discovery'
        | 'service-design'
        | 'requirements'
        | 'ai-product-development'
        | 'process-operations'
        | 'business-modeling'
        | 'technical-pm'
        | 'documentation-spec'
        | 'analytics-experimentation'
        | 'ux-direction'
        | 'stakeholder-management'
        | 'fintech-strategy'
        | 'rtl-persian'
        | 'gamification'
        | 'product-function-setup';
      /**
       * Short display form, e.g. "Service Design"
       */
      label: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'capabilityEvidence';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilityModelBlock".
 */
export interface CapabilityModelBlock {
  sectionHeader?: SectionHeaderField;
  /**
   * The fields the work draws on. Six reads best — the grid is two or three columns, so six fills it exactly.
   */
  disciplines: {
    label: string;
    id?: string | null;
  }[];
  /**
   * Small label over the result, e.g. "Feeding"
   */
  outputLabel: string;
  /**
   * What they all feed, e.g. "System · Decision · Delivery"
   */
  output: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'capabilityModel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectArchiveBlock".
 */
export interface ProjectArchiveBlock {
  sectionHeader?: SectionHeaderField;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projectArchive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CareerJourneyBlock".
 */
export interface CareerJourneyBlock {
  sectionHeader?: SectionHeaderField;
  stages?:
    | {
        /**
         * Company/role/period authority — edit facts on the Experiences collection, not here.
         */
        experience: string | Experience;
        /**
         * What changed in Sina’s thinking or responsibility at this stage — not a duties list.
         */
        narrative: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Optional plain-text reference, e.g. "Selected work → Digital Gold" — no /work route exists yet to link to.
         */
        relatedProjectLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'careerJourney';
}
/**
 * Company/role/period reference data — no confirmed calendar dates exist yet, so periods are shown as a duration label, not a year.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: string;
  /**
   * Admin-facing row title, e.g. "Digikala — Digital Gold".
   */
  title: string;
  company: string;
  /**
   * Business unit or product, if different from the company, e.g. "Digital Gold".
   */
  product?: string | null;
  /**
   * Verbatim resume role string — do not silently resolve title ambiguities.
   */
  role: string;
  employment: 'full-time' | 'part-time' | 'freelance' | 'contract';
  /**
   * Leave start/end empty until real calendar dates are confirmed — the duration label is the only date-shaped fact seeded today.
   */
  period?: {
    start?: string | null;
    end?: string | null;
    present?: boolean | null;
    approx?: boolean | null;
    /**
     * e.g. "2.5 yrs" — resume-sourced, the only duration shown until dates are confirmed.
     */
    durationLabel?: string | null;
  };
  /**
   * Plain text, e.g. "fintech" — not a relationship, to avoid taxonomy scope creep.
   */
  domain?: string | null;
  /**
   * One line, resume-sourced.
   */
  summary: string;
  /**
   * Manual sort key (resume order).
   */
  order: number;
  /**
   * Tick per language once a native speaker has reviewed this locale. Machine-drafted locales stay unticked.
   */
  translationReviewed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThinkingMapBlock".
 */
export interface ThinkingMapBlock {
  sectionHeader?: SectionHeaderField;
  /**
   * Optional short intro above the diagram.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Exactly 6, in this order: Business, Product, User, System, Execution, Learning — the diagram layout is fixed to this order.
   */
  nodes?:
    | {
        label: string;
        /**
         * Short — one sentence.
         */
        annotation?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'thinkingMap';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrinciplesBlock".
 */
export interface PrinciplesBlock {
  sectionHeader?: SectionHeaderField;
  items?:
    | {
        /**
         * Short, specific — avoid slogans ("Design with empathy").
         */
        title: string;
        /**
         * One concise explanation — what this reveals about how decisions get made.
         */
        description: string;
        /**
         * Optional, e.g. "Seen in → Digital Gold".
         */
        evidenceLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'principles';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamProcessBlock".
 */
export interface TeamProcessBlock {
  sectionHeader?: SectionHeaderField;
  /**
   * Optional short intro above the diagram.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Exactly 6, in this order: Business Context, Product Decision, Design, Engineering, Validation, Learning.
   */
  nodes?:
    | {
        label: string;
        annotation?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Only include statements with real supporting evidence — leave empty rather than pad with generic collaboration claims.
   */
  statements?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'teamProcess';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PersonalSideBlock".
 */
export interface PersonalSideBlock {
  sectionHeader?: SectionHeaderField;
  items?:
    | {
        title: string;
        description: string;
        /**
         * Optional. Leave empty — the section works fine with typography alone.
         */
        media?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'personalSide';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NowSectionBlock".
 */
export interface NowSectionBlock {
  sectionHeader?: SectionHeaderField;
  statement: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional — leave empty until /lab exists. Do not link to a page that doesn’t exist yet.
   */
  link?: {
    url?: string | null;
    label?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'nowSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: string | Project;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'experiences';
        value: string | Experience;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        metricsStrip?: T | MetricsStripBlockSelect<T>;
        selectedWork?: T | SelectedWorkBlockSelect<T>;
        workMosaic?: T | WorkMosaicBlockSelect<T>;
        workspace?: T | WorkspaceBlockSelect<T>;
        tracks?: T | TracksBlockSelect<T>;
        workflowStages?: T | WorkflowStagesBlockSelect<T>;
        experienceCatalogue?: T | ExperienceCatalogueBlockSelect<T>;
        experienceTeaser?: T | ExperienceTeaserBlockSelect<T>;
        capabilitySpotlight?: T | CapabilitySpotlightBlockSelect<T>;
        capabilityMatrix?: T | CapabilityMatrixBlockSelect<T>;
        capabilityEvidence?: T | CapabilityEvidenceBlockSelect<T>;
        capabilityModel?: T | CapabilityModelBlockSelect<T>;
        projectArchive?: T | ProjectArchiveBlockSelect<T>;
        careerJourney?: T | CareerJourneyBlockSelect<T>;
        thinkingMap?: T | ThinkingMapBlockSelect<T>;
        principles?: T | PrinciplesBlockSelect<T>;
        teamProcess?: T | TeamProcessBlockSelect<T>;
        personalSide?: T | PersonalSideBlockSelect<T>;
        nowSection?: T | NowSectionBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  translationReviewed?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  layout?: T;
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsStripBlock_select".
 */
export interface MetricsStripBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  metrics?:
    | T
    | {
        value?: T;
        caption?: T;
        source?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeaderField_select".
 */
export interface SectionHeaderFieldSelect<T extends boolean = true> {
  tag?: T;
  lead?: T;
  tail?: T;
  lede?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SelectedWorkBlock_select".
 */
export interface SelectedWorkBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  project?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkMosaicBlock_select".
 */
export interface WorkMosaicBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  items?:
    | T
    | {
        project?: T;
        size?: T;
        mediaOverride?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkspaceBlock_select".
 */
export interface WorkspaceBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  principle?: T;
  loopLabel?: T;
  stages?:
    | T
    | {
        key?: T;
        label?: T;
        statement?: T;
        question?: T;
        description?: T;
        output?: T;
        evidence?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TracksBlock_select".
 */
export interface TracksBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  tracks?:
    | T
    | {
        key?: T;
        title?: T;
        experience?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowStagesBlock_select".
 */
export interface WorkflowStagesBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  categories?:
    | T
    | {
        key?: T;
        title?: T;
        tools?:
          | T
          | {
              toolKey?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExperienceCatalogueBlock_select".
 */
export interface ExperienceCatalogueBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  items?:
    | T
    | {
        index?: T;
        name?: T;
        companyKey?: T;
        role?: T;
        blurb?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExperienceTeaserBlock_select".
 */
export interface ExperienceTeaserBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  capabilities?:
    | T
    | {
        key?: T;
        title?: T;
        principle?: T;
        id?: T;
      };
  metrics?:
    | T
    | {
        value?: T;
        caption?: T;
        source?: T;
        id?: T;
      };
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilitySpotlightBlock_select".
 */
export interface CapabilitySpotlightBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  items?:
    | T
    | {
        key?: T;
        title?: T;
        principle?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilityMatrixBlock_select".
 */
export interface CapabilityMatrixBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  evidenceLabel?: T;
  groups?:
    | T
    | {
        key?: T;
        title?: T;
        skills?:
          | T
          | {
              key?: T;
              title?: T;
              description?: T;
              evidence?:
                | T
                | {
                    label?: T;
                    project?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilityEvidenceBlock_select".
 */
export interface CapabilityEvidenceBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  items?:
    | T
    | {
        label?: T;
        project?: T;
        note?: T;
        capabilities?:
          | T
          | {
              key?: T;
              label?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilityModelBlock_select".
 */
export interface CapabilityModelBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  disciplines?:
    | T
    | {
        label?: T;
        id?: T;
      };
  outputLabel?: T;
  output?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectArchiveBlock_select".
 */
export interface ProjectArchiveBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CareerJourneyBlock_select".
 */
export interface CareerJourneyBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  stages?:
    | T
    | {
        experience?: T;
        narrative?: T;
        relatedProjectLabel?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThinkingMapBlock_select".
 */
export interface ThinkingMapBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  intro?: T;
  nodes?:
    | T
    | {
        label?: T;
        annotation?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PrinciplesBlock_select".
 */
export interface PrinciplesBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        evidenceLabel?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamProcessBlock_select".
 */
export interface TeamProcessBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  intro?: T;
  nodes?:
    | T
    | {
        label?: T;
        annotation?: T;
        id?: T;
      };
  statements?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PersonalSideBlock_select".
 */
export interface PersonalSideBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NowSectionBlock_select".
 */
export interface NowSectionBlockSelect<T extends boolean = true> {
  sectionHeader?: T | SectionHeaderFieldSelect<T>;
  statement?: T;
  link?:
    | T
    | {
        url?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  role?: T;
  summary?: T;
  kind?: T;
  period?:
    | T
    | {
        start?: T;
        end?: T;
        present?: T;
      };
  industry?: T;
  team?: T;
  projectStatus?: T;
  tools?: T;
  cover?: T;
  liveUrl?: T;
  statement?: T;
  hero?: T | CaseStudyHeroSelect<T>;
  snapshot?: T | CaseStudySnapshotSelect<T>;
  sections?:
    | T
    | {
        csNarrative?: T | CaseStudyNarrativeBlockSelect<T>;
        csFigure?: T | CaseStudyFigureBlockSelect<T>;
        csFinding?: T | CaseStudyFindingBlockSelect<T>;
        csProcess?: T | CaseStudyProcessBlockSelect<T>;
        csOwnership?: T | CaseStudyOwnershipBlockSelect<T>;
        csDecisions?: T | CaseStudyDecisionsBlockSelect<T>;
        csOutcomes?: T | CaseStudyOutcomesBlockSelect<T>;
        csLessons?: T | CaseStudyLessonsBlockSelect<T>;
      };
  nextProject?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  featured?: T;
  order?: T;
  caseStudyStatus?: T;
  translationReviewed?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyHero_select".
 */
export interface CaseStudyHeroSelect<T extends boolean = true> {
  items?:
    | T
    | {
        media?: T;
        id?: T;
      };
  caption?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudySnapshot_select".
 */
export interface CaseStudySnapshotSelect<T extends boolean = true> {
  problem?: T;
  role?: T;
  result?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyNarrativeBlock_select".
 */
export interface CaseStudyNarrativeBlockSelect<T extends boolean = true> {
  label?: T;
  customLabel?: T;
  heading?: T;
  body?: T;
  insight?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyFigureBlock_select".
 */
export interface CaseStudyFigureBlockSelect<T extends boolean = true> {
  layout?: T;
  treatment?: T;
  items?:
    | T
    | {
        media?: T;
        caption?: T;
        id?: T;
      };
  annotations?:
    | T
    | {
        text?: T;
        id?: T;
      };
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyFindingBlock_select".
 */
export interface CaseStudyFindingBlockSelect<T extends boolean = true> {
  kind?: T;
  text?: T;
  attribution?: T;
  method?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyProcessBlock_select".
 */
export interface CaseStudyProcessBlockSelect<T extends boolean = true> {
  heading?: T;
  kind?: T;
  steps?:
    | T
    | {
        code?: T;
        label?: T;
        note?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyOwnershipBlock_select".
 */
export interface CaseStudyOwnershipBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  own?: T;
  coOwn?: T;
  collaborate?: T;
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyDecisionsBlock_select".
 */
export interface CaseStudyDecisionsBlockSelect<T extends boolean = true> {
  heading?: T;
  lede?: T;
  items?:
    | T
    | {
        title?: T;
        why?: T;
        alternatives?: T;
        tradeoff?: T;
        evidence?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyOutcomesBlock_select".
 */
export interface CaseStudyOutcomesBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        context?: T;
        kind?: T;
        source?: T;
        id?: T;
      };
  shipped?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyLessonsBlock_select".
 */
export interface CaseStudyLessonsBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  product?: T;
  role?: T;
  employment?: T;
  period?:
    | T
    | {
        start?: T;
        end?: T;
        present?: T;
        approx?: T;
        durationLabel?: T;
      };
  domain?: T;
  summary?: T;
  order?: T;
  translationReviewed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Short blurb under the wordmark.
   */
  description?: string | null;
  social?:
    | {
        kind: 'email' | 'linkedin' | 'telegram' | 'instagram' | 'dribbble' | 'behance';
        /**
         * Full URL, or mailto:.
         */
        href: string;
        ariaLabel: string;
        id?: string | null;
      }[]
    | null;
  pagesTitle?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * aria-label for the nav; defaults to "Footer navigation" if left blank.
   */
  navLabel?: string | null;
  about?: {
    title?: string | null;
    text?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
  };
  contact?: {
    title?: string | null;
    text?: string | null;
    linkLabel?: string | null;
    /**
     * e.g. /contact or mailto:you@example.com
     */
    linkHref?: string | null;
  };
  metaBlock?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  legalLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: string;
  name?: string | null;
  /**
   * Small resume-style line, e.g. "Product Designer & Manager".
   */
  headline?: string | null;
  /**
   * ≤ 12 words, optional.
   */
  tagline?: string | null;
  /**
   * ~20-word one-liner, used for SEO/footer.
   */
  bioShort?: string | null;
  /**
   * Left empty — not yet confirmed.
   */
  basedIn?: string | null;
  /**
   * Seeded as Freelance, evidenced by the independent projects in Docs/Experience/Projects/. The other three are still unconfirmed (Brand-Brief Q3).
   */
  openTo?: ('full-time' | 'freelance' | 'consulting' | 'advisory')[] | null;
  /**
   * Optional. Leave empty unless a genuinely appropriate editorial portrait exists.
   */
  portrait?: (string | null) | Media;
  /**
   * The downloadable CV (PDF).
   */
  resume?: (string | null) | Media;
  links?:
    | {
        platform: 'email' | 'linkedin' | 'dribbble' | 'behance';
        url: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  social?:
    | T
    | {
        kind?: T;
        href?: T;
        ariaLabel?: T;
        id?: T;
      };
  pagesTitle?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  navLabel?: T;
  about?:
    | T
    | {
        title?: T;
        text?: T;
        linkLabel?: T;
        linkHref?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        text?: T;
        linkLabel?: T;
        linkHref?: T;
      };
  metaBlock?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  copyright?: T;
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  name?: T;
  headline?: T;
  tagline?: T;
  bioShort?: T;
  basedIn?: T;
  openTo?: T;
  portrait?: T;
  resume?: T;
  links?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: string | Project;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: string | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}